apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IEfm/VDbKnHlL6zI7N6WIHYo5DJ9wGj/kmijKmltCuU+t2w5ODRr9tdZ4s4tGuy5L640/kdzcic0Rg+93b2sBjmj931xjWBxhLtYjLY8ciMzd3KrqmACZ32Q3DwP2wR1IE0DZ4dkHo1a7izi+nW2eScHtuHc3iwkv/FDrNJKwVwxNC7vF6Ak6cLtow/UBwbsq5PRyTIvKOIkoJb442tczNaPWGr9MSILGsPBfhGEp9mUM0zDF3Dh7rfmQZqftiCqYjVOxmixb38bejLXRpknsuLgYcZsGnKi/aAmSdwg/l4M5RBlM4JDvVJ1OL0pTfaHwKOdN6mJu3gEbjkkVNjNBcP9UmTNSa+t+SExQxxm74KwoOB8uazYkz/OJWJV7QqB,iv:+6FVFNImQUL1XjCiC2PLR6jHWpa9w2Y9EuZ3RZwITdM=,tag:QhcWFJeR7utm9VQPK3cQUg==,type:str]
    identity.pub: ENC[AES256_GCM,data:YmdyjqH2AAzl1XDu/tldRQiwcx+HHcyWRlYarhKPPbeVP8Z6Pgguo+KH2jFDmgCdc3hXwNIFZoistu8N0B9g0DW6HSefJG9FavS5B0AOV6QUoO4mLdPY4fxxZqjJSTUZ1jYS//N+V+vZrB+2rT9uf4wnRfor1vFxOG3upaTQf6sjdWp1/YaPeGAgZrGqLKIuMtBPtpPOz61w5Aq4Wb5mILFNSaGW+vhwf/BWu3lCc+ts0sNtgthNK2jI9L5odVTQq5y8tdyKsdEYOiUypw==,iv:NClIoNa7p7MyuVMVnGu56i8NPzQJvtduoavm3Bmo6Dw=,tag:HOhB+JAxocSvxszIjY9g5g==,type:str]
    known_hosts: ENC[AES256_GCM,data:hJN9DH936yMZUdagAakJca90+KMSeJboeqXzeOCZV/4I9QrNN4FO8mgjfi9G4YuJ80zQIkgnI7zDtU05bN9eWX576T4OmJY7IN5KNg93gH4HuqpLfw00dwyIY5FUudV9JJE3pK0k2I2tBBTWjlSPUo2FWKP2wPPYUD5njzuIfoo7hTq8GWiZJl/zqgDR7zVJsuOrIyjWuaNzuTXiC1B4X2TNVJmYa+RFf8wg,iv:nR3ydu+231s2FQegElU/DN0no8n1eEXGR/K026JAjRk=,tag:RaQnFBsEZ/aeXI1Lq70Ofw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ya07hv3a9wuvuk62qd2trzt24wrc30zw0fawfr7tjmc2rxp9yvzs7tdfp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZWtQek9lUkJGdjZUWm03
            bEVMMGlDQlQrU2xSUG80ZnlKK1BGaGU3WmhVCjVSMWdNOFRJbFc5L3duaHNtVGpr
            M0VnalI4S3RtSkdiZk1nN29Md2pKNVUKLS0tIDljSGZUNlNkeWdmMk51ZmJ6dnJ0
            L0xhSlNmNWRmZlpEaFJoTnFhclZYUjQKspDYhoVaEVGEHCFf3zh+prggr4MQv8Kt
            N45fG0DQPPIji5iUKai0ph0loTa840glCnjszZN+nFIueZHlTcD2tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-15T03:30:58Z"
    mac: ENC[AES256_GCM,data:lt9N6l5jivvkNai4mLOXu8XvOYLAlPC5tHziyU8G6I0jTK4gOxEtxUI946NjGQtafR70Zb6SxVvGQcCO+grvGL5ULZUPx8NosF+9zswOr8A0z0HwhjpIVaZPwPI5w6LbA2TA4Leje4aK8kauINju5m8DpFzMwiTukXUUSx1nnWo=,iv:sdQaquRzj51kWqebDGM1dMEJBZ3QHXqo+rYMiczXu98=,tag:BFN8UuNTKnGhqNABnEfpXg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
