apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloud
  namespace: ext-service
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 15.1.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Chicago
    global:
      stopAll: false
    service:
      main:
        type: ExternalIP
        externalIP: ${TRUENAS_IP}
        ports:
          main:
            protocol: http
            port: 9001
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          #   middlewares:
          #     - name: local
          #       namespace: traefik
          #     - name: bouncer
          #       namespace: traefik
          #   entrypoints:
          #     - websecure
          # certManager:
          #   enabled: true
          #   certificateIssuer: cluster-cert

        tls:
          - hosts:
              - cloud.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard

        hosts:
          - host: cloud.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix                                